version: 2
cli:
  server: https://app.fossa.com
  fetcher: custom
  project: github.com/GrindrodBank/dokuti
analyze:
  modules:
  - name: za.co.grindrodbank:dokuti
    type: mvn
    target: za.co.grindrodbank:dokuti
    path: .