spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/dokuti
    initialization-mode: always
    username: "postgres"
    password: "postgres"
  jpa:
    show-sql: false
    hibernate:
      #ddl-auto: update
      ddl-auto: validate
    properties: 
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: "_documents"
  flyway:
    enabled: true
    #enabled: false
  
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB 
     
storage:
  location: "/tmp/dokuti-local-uploads"

#Security Properties
rest:
  security:
    # This property toggles whether Oauth 2.0 based security is enabled. A 'disabled' value removes all security.
    enabled: true
    issuerUri: "http://keycloak.local/auth/realms/Dokuti"
    apiMatcher: "/**"
    cors:
      allowedOrigins: "*"
      allowed-headers: "*"
      allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
      maxAge: 3600

# This section is only used of rest.security.enabled = true
security:
  oauth2:
    resource:
      id: dokuti
      tokenInfoUri: ${rest.security.issuerUri}/protocol/openid-connect/token/introspect
      userInfoUri: ${rest.security.issuerUri}/protocol/openid-connect/userinfo
      jwt:
        keyValue: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmulcajWJq15GpDmlfwVDw94vOnrk3TS/GP4S8wZvbulZbGna1kFR1usHiz4CXWE6xb9s2D820crj2ERsubNbe6GLNLynLDUui85QcHQhvb8wXUvq9+d4SckYpLujys//qU77AuhC7Xbutw8+UC8qlw0niF3kbLnx2rCpN0cbad6T0uFBRbAvS8EwHDm1Ta/em+VXoPQE3baQoawSMRjSnuxB2JAnof8fijxGPRQhxnQGUa1bwh7lgV2ClPGZ6WfzW25yInQY8Yni0bKJ0vsR/NgetB1JOLFiAgoFRn5IHbft4Hv+tVLBAsZRnhuu8mXtNY8YNiaLVM2FuuSg/EHOrwIDAQAB\n-----END PUBLIC KEY-----"

# This setting exposes all the actuator routes, some of which expose sensitive info. Ensure that only the /health route is exposed
# publically for readiness and liveness probes in non-dev environments.
management:
  endpoints:
    web:
      exposure:
        include: "info, health"
        
logging:
  level:
    root: INFO
    za.co.grindrodbank.dokuti: DEBUG
  