version: 2
jobs:
  test:
    docker:
      - image: maven:3.5.3-jdk-8-alpine
    working_directory: ~/dokuti-build
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - dokuti-build-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: dokuti-build-{{ checksum "pom.xml" }}

      - run: mvn test
  sonarqube:
    docker:
      - image: maven:3.5.3-jdk-8-alpine
    working_directory: ~/dokuti-sonarqube
    steps:
      - checkout
      - restore_cache:
          keys:
            - dokuti-sonarqube-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: dokuti-sonarqube-{{ checksum "pom.xml" }}
      - run: |
         mvn clean
         mvn package \
                -Dmaven.test.skip=true \
            org.jacoco:jacoco-maven-plugin:prepare-agent \
            sonar:sonar \
                -Dsonar.host.url=https://sonarcloud.io \
                -Dsonar.projectKey=GrindrodBank_dokuti \
                -Dsonar.organization=grindrodbank \
                -Dsonar.login=$SONAR_AUTH_TOKEN \
                -Dsonar.branch.name=$CIRCLE_BRANCH \
                -Dsonar.exclusions=srcgen/**/*
  docker-build:
    docker:
      - image: docker
    working_directory: ~/dokuti-docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # build and push Docker image to dockerhub.
      - run: |
          TAG=0.2.$CIRCLE_BUILD_NUM
          docker build -t grindrodbank/dokuti:$TAG .     
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push grindrodbank/dokuti:$TAG
  fossa-scan:
    docker:
      - image: circleci/golang:1.8
    working_directory: ~/dokuti-build
    steps:
      - run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/dokuti-build
      - run: pwd
      - run: ls -lah
      - run: fossa init
      - run: FOSSA_API_KEY=$FOSSA_API_KEY fossa analyze
  compile:
    docker:
      - image: maven:3.5.3-jdk-8-alpine
    working_directory: ~/dokuti-build
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - dokuti-compile-{{ checksum "pom.xml" }}

      - run: mvn compile
      - run: ls -lah

      - save_cache:
          paths:
            - ~/.m2
          key: dokuti-compile-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
          # taken to be the root directory of the workspace.
          root: ~/
          paths: 
            - dokuti-build
workflows:
  version: 2
  build-master:
    jobs:
      - test
      - sonarqube
      - compile
      - fossa-scan:
          requires:
            - compile
      - docker-build:
          requires:
            - test
            - sonarqube
          filters:
            branches:
              only: master