version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: maven:3.5.3-jdk-8-alpine

    working_directory: ~/dokuti-build

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dokuti-build-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: dokuti-build-{{ checksum "pom.xml" }}

      - run: mvn test
  sonarqube:
    docker:
      # specify the version you desire here
      - image: maven:3.5.3-jdk-8-alpine
    working_directory: ~/dokuti-sonarqube
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dokuti-sonarqube-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: dokuti-sonarqube-{{ checksum "pom.xml" }}

      - run: |
         mvn clean
         mvn package \
                -Dmaven.test.skip=true \
            org.jacoco:jacoco-maven-plugin:prepare-agent \
            sonar:sonar \
                -Dsonar.host.url=https://sonarcloud.io \
                -Dsonar.projectKey=dokuti \
                -Dsonar.organization=grindrodbank \
                -Dsonar.login=$SONAR_AUTH_TOKEN \
                -Dsonar.exclusions=srcgen/**/*
  docker-build:
    docker:
      - image: docker
    working_directory: ~/dokuti-docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # build and push Docker image
      - run: |
          TAG=0.2.$CIRCLE_BUILD_NUM
          docker build -t grindrodbank/dokuti:$TAG .     
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push grindrodbank/dokuti:$TAG
workflows:
  version: 2
  build-master:
    jobs:
      - test
      - sonarqube:
          filters:
            branches:
              only: master
      - docker-build:
          requires:
            - test
            - sonarqube
          filters:
            branches:
              only: master
