version: '3.4'
x-defaults: &defaults
  image: sentry:9.1
  depends_on:
    - redis
    - postgres
  env_file: .env
  environment:
    SENTRY_REDIS_HOST: redis
    SENTRY_POSTGRES_HOST: postgres
  # volumes:
  #   - sentry-data:/var/lib/sentry/files

services:
  redis:
    image: redis:3.2-alpine

  postgres:
    image: postgres:9.5
    volumes:
      - sentry-postgres:/var/lib/postgresql/data

  web:
    <<: *defaults
    ports:
      - "9000:9000"

  cron:
    <<: *defaults
    command: run cron

  worker:
    <<: *defaults
    command: run worker

volumes:
  sentry-postgres:
    external: true
  # sentry-data:
  #   external: true
