version: '3'
services:
  postgresql:
    image: "bitnami/postgresql:10.7.0"
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=dokuti
    ## To persist database
    # volumes:
    #   - 'postgresql_data:/bitnami'
  web:
    build: ../../
    ports:
     - "8181:8080"
    volumes:
      - ./sample-application.yaml:/config/application.yaml
      - ./files:/tmp/dokuti-local-uploads
    depends_on:
      - postgresql
    entrypoint: sh -c './wait-for.sh postgresql:5432 -- ./entrypoint.sh' 

  keycloak:
    image: "jboss/keycloak:4.7.0.Final"
    ports:
     - "9191:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: "/tmp/dokuti-realm.json"
    volumes:
      - ./dokuti-realm.json:/tmp/dokuti-realm.json
         

